### ISSUE TITLE
shows errors and doesnt work

### ISSUE THREAD

**Issue by Waifuwithdanaifu** [Fukki/auto-target#18]
}
error: Cannot read property 'isArray' of undefined
    at V (C:\Users\XX\Desktop\tera-toolbox-master\mods\auto-target-master\index.js:1:233010)
    at Object.PsSWp (C:\Users\XX\Desktop\tera-toolbox-master\mods\auto-target-master\index.js:1:115010)
    at Object.callback (C:\Users\XX\Desktop\tera-toolbox-master\mods\auto-target-master\index.js:1:179265)
[13:39:03.977] [dispatch] [auto target] handle: error running hook for S_ABNORMALITY_BEGIN<4>
hook: (anonymous) in auto target
data: {
  target: 288371113642566181n,
  source: 0n,
  id: 5020017,
  duration: 2147483647n,
  stacks: 1,
  hitCylinderId: 0,
  unk3: 0
}

**Comment by Fukki** [comment]
should be fix :c
