### ISSUE TITLE
[auto target] hook: Error: obsolete definition (S_PARTY_MEMBER_LIST.8)

### ISSUE THREAD

**Issue by Loliconera** [Fukki/auto-target#20]
```
[17:51:48.227] [mods] ERROR: El modulo "AT" (Auto Target) no pudo aplicar su componente de red al servidor!
[17:51:48.228] [mods] ERROR: Contactate con el autor del modulo:: https://github.com/Fukki/auto-target/issues/
[17:51:48.228] Error: [dispatch] [auto target] hook: Error: obsolete definition (S_PARTY_MEMBER_LIST.8)
    at Dispatch.createHook (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:230:27)
    at Dispatch.hook (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27)
    at Proxy.hook (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\bin\mod.js:280:36)
    at new DY (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:179112)
    at new <anonymous> (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\bin\mod-legacy-wrapper.js:144:13)
    at Mod.loadNetworkInstance (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\bin\mod.js:595:31)
    at ModManager.loadNetwork (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:252:20)
    at C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllNetwork (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:231:25)
```

**Comment by pepsimemen** [comment]
change S_PARTY_MEMBER_LIST from 8 to 9 ez

**Comment by Loliconera** [comment]
> cambiar S_PARTY_MEMBER_LIST de 8 a 9 ez


the module is encrypted

**Comment by Fukki** [comment]
fixed

**Comment by Noheadman** [comment]
Can you please make separate version of mod for Menma's TERA which uses older patch?
