### ISSUE TITLE
Error: obsolete definition (S_ABNORMALITY_BEGIN.4)

### ISSUE THREAD

**Issue by FrankMora** [Fukki/auto-target#22]
```
[13:47:34.557] Error: [dispatch] [auto target] hook: Error: obsolete definition (S_ABNORMALITY_BEGIN.4)
    at Dispatch.createHook (G:\Games\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:230:27)
    at Dispatch.hook (G:\Games\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27)
    at Proxy.hook (G:\Games\TeraToolbox\bin\mod.js:280:36)
    at new hb (G:\Games\TeraToolbox\mods\auto-target-master\index.js:1:247569)
    at new <anonymous> (G:\Games\TeraToolbox\bin\mod-legacy-wrapper.js:144:13)
    at Mod.loadNetworkInstance (G:\Games\TeraToolbox\bin\mod.js:595:31)
    at ModManager.loadNetwork (G:\Games\TeraToolbox\bin\mod-manager.js:252:20)
    at G:\Games\TeraToolbox\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllNetwork (G:\Games\TeraToolbox\bin\mod-manager.js:231:25)
```

**Comment by Fukki** [comment]
restart toolbox to autoupdate
