### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by unlimitedgtx** [Fukki/auto-target#4]
Module need update after patch 95. Didnt work in new instance

**Comment by Fukki** [comment]
added new target type in config "npc-auto"

**Comment by unlimitedgtx** [comment]
After update, theres no config file anymore. And my skills wont work anymore. Every lockon doesnt work for example energy stars wont lock on. at the beginning of the fight i can cast it, but then i cant target the boss

**Comment by unlimitedgtx** [comment]
[19:51:06.057] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 21467313n,
  maxHp: 27448770n,
  diff: -5952686n,
  type: 0,
  target: 3519330562286319n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:06.060] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 6239527n,
  maxHp: 12448782n,
  diff: -6178402n,
  type: 0,
  target: 3519330562416324n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:06.062] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 6317136n,
  maxHp: 12448782n,
  diff: -6100942n,
  type: 0,
  target: 3519330562419950n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:06.064] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 21296128n,
  maxHp: 27448770n,
  diff: -6122100n,
  type: 0,
  target: 3519330562419071n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:06.065] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 6146718n,
  maxHp: 12448782n,
  diff: -6271642n,
  type: 0,
  target: 3519330562419530n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:07.006] [dispatch] [auto target] handle: error running hook for S_TARGET_INFO<2>
hook: (anonymous) in auto target
data: {
  target: 3519330562419530n,
  hpPercentage: 0.4937605857849121,
  mpPercentage: 0,
  level: 67,
  itemLevel: 0,
  stPercentage: 0,
  edge: 0,
  edgePercentage: 0,
  edgeTimeRemaining: 0,
  edgeMin: 0,
  abnormals: [
    { id: 201801, duration: 37831n, stacks: 1 },
    { id: 201799, duration: 2147483647n, stacks: 1 }
  ],
  conditions: []
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:336504)
[19:51:07.286] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 14148380n,
  maxHp: 27448770n,
  diff: -7147748n,
  type: 0,
  target: 3519330562419071n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:08.017] [dispatch] [auto target] handle: error running hook for S_TARGET_INFO<2>
hook: (anonymous) in auto target
data: {
  target: 3519330562419530n,
  hpPercentage: 0.16123256087303162,
  mpPercentage: 0,
  level: 67,
  itemLevel: 0,
  stPercentage: 0,
  edge: 0,
  edgePercentage: 0,
  edgeTimeRemaining: 0,
  edgeMin: 0,
  abnormals: [
    { id: 201801, duration: 36833n, stacks: 1 },
    { id: 201799, duration: 2147483647n, stacks: 1 },
    { id: 200800, duration: 2376n, stacks: 1 },
    { id: 200302, duration: 35906n, stacks: 1 }
  ],
  conditions: []
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:336504)
[19:51:08.220] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 7923818n,
  maxHp: 27448770n,
  diff: -7363332n,
  type: 0,
  target: 3519330562420333n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:08.223] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 1394923n,
  maxHp: 12448770n,
  diff: -6482396n,
  type: 0,
  target: 3519330562416314n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:08.251] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 0n,
  maxHp: 12448782n,
  diff: -6450920n,
  type: 0,
  target: 3519330562416324n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:08.422] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 8712886n,
  maxHp: 27448770n,
  diff: -7107695n,
  type: 0,
  target: 3519330562420194n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:09.001] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 13461523n,
  maxHp: 27448770n,
  diff: -686857n,
  type: 0,
  target: 3519330562419071n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:09.080] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 11952632n,
  maxHp: 27448770n,
  diff: -1508891n,
  type: 0,
  target: 3519330562419071n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:09.564] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 8374658n,
  maxHp: 27448770n,
  diff: -3577974n,
  type: 0,
  target: 3519330562419071n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:10.029] [dispatch] [auto target] handle: error running hook for S_TARGET_INFO<2>
hook: (anonymous) in auto target
data: {
  target: 3519330562419071n,
  hpPercentage: 0.3051013946533203,
  mpPercentage: 0,
  level: 67,
  itemLevel: 0,
  stPercentage: 0,
  edge: 0,
  edgePercentage: 0,
  edgeTimeRemaining: 0,
  edgeMin: 0,
  abnormals: [],
  conditions: []
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:336504)
[19:51:10.144] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 6769210n,
  maxHp: 27448770n,
  diff: -1605448n,
  type: 0,
  target: 3519330562419071n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
[19:51:11.014] [dispatch] [auto target] handle: error running hook for S_TARGET_INFO<2>
hook: (anonymous) in auto target
data: {
  target: 3519330562419071n,
  hpPercentage: 0.24661250412464142,
  mpPercentage: 0,
  level: 67,
  itemLevel: 0,
  stPercentage: 0,
  edge: 0,
  edgePercentage: 0,
  edgeTimeRemaining: 0,
  edgeMin: 0,
  abnormals: [],
  conditions: []
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:336504)
[19:51:11.125] [dispatch] [auto target] handle: error running hook for S_CREATURE_CHANGE_HP<6>
hook: (anonymous) in auto target
data: {
  curHp: 5581636n,
  maxHp: 27448770n,
  diff: -1187574n,
  type: 0,
  target: 3519330562419071n,
  source: 140737490216637n,
  crit: 0,
  abnormId: 0
}
error: Cannot set property 'relation' of undefined
    at Object.callback (C:\Users\priva\AppData\Local\Programs\TeraToolbox\mods\auto-target-master\index.js:1:335499)
